package com.example.frozen

const val SAMPLE_TEXT = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur a erat nam at lectus urna duis. In hendrerit gravida rutrum quisque non. Vulputate mi sit amet mauris commodo quis. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Non enim praesent elementum facilisis leo vel fringilla. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Senectus et netus et malesuada fames ac turpis egestas maecenas. Accumsan in nisl nisi scelerisque eu. Hac habitasse platea dictumst vestibulum. Gravida quis blandit turpis cursus in hac habitasse. Mi proin sed libero enim sed faucibus turpis. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Fermentum iaculis eu non diam phasellus vestibulum lorem. Cursus vitae congue mauris rhoncus aenean. Sed augue lacus viverra vitae congue.

Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Nunc sed id semper risus. Nulla aliquet enim tortor at auctor urna nunc id. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Tellus rutrum tellus pellentesque eu tincidunt. Egestas erat imperdiet sed euismod nisi porta lorem. Urna nec tincidunt praesent semper. Id faucibus nisl tincidunt eget nullam non nisi est. Nisi porta lorem mollis aliquam ut porttitor leo. Ut ornare lectus sit amet est. Elementum nibh tellus molestie nunc non blandit massa enim nec. Semper viverra nam libero justo laoreet sit amet cursus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Vel pharetra vel turpis nunc. Pulvinar elementum integer enim neque volutpat ac.

Volutpat est velit egestas dui. Odio aenean sed adipiscing diam donec adipiscing. Condimentum lacinia quis vel eros donec ac odio tempor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Iaculis nunc sed augue lacus viverra vitae. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Elementum integer enim neque volutpat ac tincidunt vitae. Platea dictumst vestibulum rhoncus est pellentesque. Blandit massa enim nec dui. Faucibus interdum posuere lorem ipsum dolor sit amet. Mattis enim ut tellus elementum sagittis vitae et leo.

Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Id diam maecenas ultricies mi eget mauris pharetra et. Elementum curabitur vitae nunc sed velit dignissim. Feugiat in ante metus dictum. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Velit laoreet id donec ultrices tincidunt arcu non sodales. Sit amet tellus cras adipiscing enim eu. Augue mauris augue neque gravida in fermentum et sollicitudin ac. In vitae turpis massa sed. Volutpat diam ut venenatis tellus.

Nisi est sit amet facilisis magna. Turpis in eu mi bibendum neque egestas congue quisque egestas. Imperdiet proin fermentum leo vel orci. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Vivamus arcu felis bibendum ut tristique et. Id nibh tortor id aliquet lectus proin. Tincidunt id aliquet risus feugiat. Venenatis a condimentum vitae sapien. Morbi tristique senectus et netus et malesuada fames ac. Sapien et ligula ullamcorper malesuada proin. Quisque id diam vel quam elementum pulvinar etiam. Netus et malesuada fames ac turpis.

Tempor orci dapibus ultrices in iaculis nunc sed augue. Auctor eu augue ut lectus arcu. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Tempor nec feugiat nisl pretium fusce. Quam pellentesque nec nam aliquam sem et tortor. Arcu ac tortor dignissim convallis aenean et. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Massa ultricies mi quis hendrerit dolor magna. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Facilisis sed odio morbi quis. Quis ipsum suspendisse ultrices gravida dictum. Enim blandit volutpat maecenas volutpat blandit aliquam. Libero enim sed faucibus turpis in eu. Dignissim enim sit amet venenatis urna cursus. Vitae congue mauris rhoncus aenean. Cras tincidunt lobortis feugiat vivamus at augue eget. Pellentesque nec nam aliquam sem.

Urna condimentum mattis pellentesque id nibh tortor. Duis at consectetur lorem donec. Est placerat in egestas erat imperdiet sed. Sed risus pretium quam vulputate. Nibh ipsum consequat nisl vel pretium. Ultricies tristique nulla aliquet enim tortor at auctor. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Non diam phasellus vestibulum lorem sed risus. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Lacus vel facilisis volutpat est velit egestas dui. Potenti nullam ac tortor vitae purus.

Est velit egestas dui id ornare arcu odio ut. Vitae et leo duis ut diam quam nulla. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Vitae purus faucibus ornare suspendisse sed nisi lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Auctor eu augue ut lectus arcu bibendum. Id porta nibh venenatis cras sed felis eget velit aliquet. Mi quis hendrerit dolor magna eget est lorem. Nibh nisl condimentum id venenatis a.

Amet nisl suscipit adipiscing bibendum est ultricies integer. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. A cras semper auctor neque vitae tempus. Cursus risus at ultrices mi tempus. Risus nec feugiat in fermentum posuere urna. Arcu dui vivamus arcu felis bibendum ut. Velit laoreet id donec ultrices tincidunt arcu. Amet mauris commodo quis imperdiet massa tincidunt nunc. Sollicitudin nibh sit amet commodo nulla facilisi. Duis at tellus at urna condimentum mattis. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Pharetra et ultrices neque ornare aenean euismod. Rhoncus urna neque viverra justo nec ultrices dui sapien.

Quis auctor elit sed vulputate. Consectetur adipiscing elit pellentesque habitant. Volutpat est velit egestas dui id ornare arcu odio. Elementum integer enim neque volutpat ac tincidunt. Adipiscing bibendum est ultricies integer quis auctor elit. Consequat mauris nunc congue nisi. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Enim nec dui nunc mattis enim ut tellus. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Est ultricies integer quis auctor elit sed.

Mattis enim ut tellus elementum sagittis vitae et leo duis. Tortor posuere ac ut consequat semper viverra nam libero justo. Et ligula ullamcorper malesuada proin libero nunc. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Urna nunc id cursus metus aliquam. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Vitae congue eu consequat ac. Purus gravida quis blandit turpis cursus in hac. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Auctor elit sed vulputate mi. Lectus nulla at volutpat diam ut venenatis tellus in metus. Morbi non arcu risus quis varius quam. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Lacus vestibulum sed arcu non odio euismod lacinia at. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Nisl suscipit adipiscing bibendum est ultricies integer. Platea dictumst quisque sagittis purus sit amet volutpat. Mauris a diam maecenas sed enim ut sem.

Augue neque gravida in fermentum et sollicitudin. Ornare aenean euismod elementum nisi quis eleifend. At elementum eu facilisis sed odio. Vulputate odio ut enim blandit volutpat. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Turpis egestas maecenas pharetra convallis posuere morbi leo. Sed egestas egestas fringilla phasellus faucibus. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sed egestas egestas fringilla phasellus faucibus. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing. Justo eget magna fermentum iaculis eu non diam. A condimentum vitae sapien pellentesque. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Mauris rhoncus aenean vel elit scelerisque mauris. Eu augue ut lectus arcu bibendum at varius vel. Scelerisque purus semper eget duis. Nunc eget lorem dolor sed viverra ipsum nunc aliquet. Ultrices neque ornare aenean euismod elementum nisi quis eleifend.

Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Erat imperdiet sed euismod nisi. Sit amet luctus venenatis lectus magna. Porttitor eget dolor morbi non arcu risus quis varius quam. Non sodales neque sodales ut. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. A arcu cursus vitae congue mauris rhoncus aenean. Suspendisse potenti nullam ac tortor vitae purus faucibus. Est ultricies integer quis auctor. Amet luctus venenatis lectus magna fringilla urna.

Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Lectus arcu bibendum at varius. Morbi tristique senectus et netus et malesuada. Nulla facilisi etiam dignissim diam quis. Nibh sit amet commodo nulla facilisi nullam vehicula. Non enim praesent elementum facilisis. Gravida dictum fusce ut placerat. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Nibh praesent tristique magna sit amet purus gravida. Convallis aenean et tortor at risus. Odio morbi quis commodo odio aenean. Pretium lectus quam id leo in. Leo duis ut diam quam. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Viverra nam libero justo laoreet sit amet.

Auctor elit sed vulputate mi sit amet mauris commodo quis. Ornare aenean euismod elementum nisi quis eleifend quam. Faucibus et molestie ac feugiat. Pharetra vel turpis nunc eget lorem. Fermentum posuere urna nec tincidunt praesent. Interdum velit euismod in pellentesque. Natoque penatibus et magnis dis parturient montes nascetur. Massa sapien faucibus et molestie. Ac odio tempor orci dapibus ultrices in iaculis. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Ante in nibh mauris cursus. Rhoncus mattis rhoncus urna neque viverra. Dui faucibus in ornare quam viverra. Elit pellentesque habitant morbi tristique senectus et. Ultrices neque ornare aenean euismod.
"""